<a href="https://colab.research.google.com/github/Caterpillar-T/MAT-421/blob/main/Homework_4_MAT_421.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 4 MAT 421

Kyle Tucker

**Section 19.1: Root Finding Problem Statement**

A root or zero function is precisely what you may think it is. There exists an $x$ for any function such that $f(x) = 0$. A simple example is $f(x) = x^4 -16$.

Of course, in less elementary cases it is not such a simple calculatoin. In such cases generating numerical approximations are much simpler and still accurate.

Lets take a look when $f(x) = \sqrt2 - x$

In [ ]:
import numpy as np
from scipy import optimize
f = lambda x: np.sqrt(2) - x
r = optimize.fsolve(f, 0)
print("r =", r)
result = f(r)
print("result=", result)

r = [1.41421356]
result= [0.]


Naturally, there are function where no root exists.
Let us take a look at an instance of that and what it outputs.

In [ ]:
f = lambda x: 5/x
r, infodict, ier, mesg = optimize.fsolve(f, 30, full_output=True)
print("r =", r)
result = f(r)
print("result=", result)
print(mesg)

r = [5.28071045e+84]
result= [9.46842295e-85]
The number of calls to function has reached maxfev = 400.


**Section 19.2: Tolerance**

Within STEM fields their exists a margin of error in most (if not all) computed values. Tolerance is the acceptable level of error.

In computer programs it is said to have converged to a solution when it has come to a solution with error smaller than the tolerance. Since we are looking for an $f(x)$ that is very close to 0, we want to find $|f(x)|$ or if we have something or have assumed something to the $n$th term it can be expressed $|x_{n+1} - x_n|$.

**Section 19.3: Bisection Method**

Something we have all seen in calculus, the intermediate value theorem, states that if $f(x)$ is continuous within the interval $[a, b]$, where $f(a) \not= f(b)$ then there must exist a $c$ such that $a < c < b$ and $f(c) = 0$.

The bisection method puts this theorem to good use as a way to find roots iteratively. In simpler terms the bisection method is calculating the midpiont between two points and if that midpoint is within tolerance then the program declares the root.

Below we will see an example when we have $f(x) = x^4 - 3$ (looking for the fourth root of 3) with $a=0$ and $b=6$ with variable tolerances.

In [ ]:
import numpy as np
def my_bisection(f, a, b, tol):
    if np.sign(f(a)) == np.sign(f(b)):
        raise Exception(
         "The scalars a and b do not bound a root")
    m = (a + b)/2

    if np.abs(f(m)) < tol:
        return m
    elif np.sign(f(a)) == np.sign(f(m)):
        return my_bisection(f, m, b, tol)
    elif np.sign(f(b)) == np.sign(f(m)):
        return my_bisection(f, a, m, tol)

In [ ]:
f = lambda x: x**4 - 3
r1 = my_bisection(f, 0, 6, 0.1)
print("r1 =", r1)
r01 = my_bisection(f, 0, 6, 0.01)
print("r01 =", r01)
print("f(r1) =", f(r1))
print("f(r01) =", f(r01))

r1 = 1.3125
r01 = 1.3154296875
f(r1) = -0.0324554443359375
f(r01) = -0.005870664651411062


**Section 19.4: Newton-Raphson Method**

The Newton-Raphson Method works by improving upon an assumed $x_0$ by taking the linear approximation of $f(x)$ around $x_0$, where we of course want our output to be as close to $0$ as possible. The linear approximation of $f(x)$ around $x_0$ is $f(x) ≈ f(x_0)+f'(x_0)(x-x_0)$.

We can use this approximation to find $x_1$ such that $f(x_1) = 0$. This would be our improvement upon $x_0$. Which would come out to be $x_1 = x_0 - \frac{f(x_0)}{f'(x_0)}$. You'll notice then that computing the improved value follows a pattern involving our previous assumed value. This is expressed as $x_i = x_{i-1} - \frac{f(x_{i-1})}{f'(x_{i-1})}$. Like the previously discussed methods the Newton-Raphson Method finds the roots iteratively until the error is within tolerance.

We will now take a look at this in action using the same example as before $f(x) = x^4 -3$ (looking for the fourth root of 3) with $x_0 = 1.3$ for our start point while comparing it to Pythons power function.

In [ ]:
#Comparison between Newton-Raphson formula and Pythons np.power function to find 4th root of 3
import numpy as np
f = lambda x: x**4 - 3
f_prime = lambda x: 4*x**3
newton_raphson = 1.3 - (f(1.3))/(f_prime(1.3))
print("newton_raphson =", newton_raphson)
print("fourth root(3) =", np.power(3,1/4))

newton_raphson = 1.3163746017296314
fourth root(3) = 1.3160740129524924


**Section 19.5: Root Finding in Python**

While the previous discussed methods are practical and useful, as one would suspect, Python has its own root-finding functions that do not require us to play around with equations. We simply just plug in our function and our guesses.

We will try this with a couple examples to see the functionality and convenience.

In [ ]:
from scipy.optimize import fsolve
f = lambda x: x**2-4
fsolve(f,[1,10])

array([-2.,  2.])

In [ ]:
from scipy.optimize import fsolve
f = lambda x: x**3 - 8
fsolve(f,[1,10])

array([2., 2.])

In [ ]:
from scipy.optimize import fsolve
f = lambda x: x**5+3*x**2-x-100
fsolve(f, [-100, 100])

array([2.42992783, 2.42992783])